FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app
COPY ./ms-number-of-users/package.json .
RUN npm install
COPY ms-number-of-users/ .
EXPOSE 3010
CMD ["npm", "start"]
